### PR TITLE
Feature: Pass external variables into YARA matching

### PR DESCRIPTION
**Pull request by Neo23x0**

### CODE REVIEW

**Comment by Eran-YT** [comment]
@Neo23x0 I need write access to the repository to resolve the conflicts

**Comment by Eran-YT** [comment]
I opened a PR that fixes the conflicts

**Comment by Neo23x0** [comment]
It builds but fails to run. 

```
Faulting application name: Raccine.exe, version: 0.0.0.0, time stamp: 0x5f95c384
Faulting module name: Raccine.exe, version: 0.0.0.0, time stamp: 0x5f95c384
Exception code: 0xc0000409
Fault offset: 0x0000000000024e4d
Faulting process id: 0x1a08
Faulting application start time: 0x01d6aafc89879cec
Faulting application path: C:\Program Files\Raccine\Raccine.exe
Faulting module path: C:\Program Files\Raccine\Raccine.exe
Report Id: 9e9e573c-3bb7-4d40-8404-62c346d4238a
Faulting package full name: 
Faulting package-relative application ID: 
```
Screenshot 2020-10-25 192815

**Comment by Eran-YT** [comment]
I don't know why that is, works fine on my machine.
What command line did you use?

**Comment by Neo23x0** [comment]
Any command line that triggers Raccine causes this crash on my machine. 

`Exception code: 0xc0000409` means `STATUS_STACK_BUFFER_OVERRUN`

**Comment by Neo23x0** [comment]
I'll start debugging ... I already found out that it happens when the YARA rules are read. 

Screenshot 2020-10-25 225217

**Comment by Neo23x0** [comment]
It seems to be a problem with the directory_iterator that I haven't seen before. 

Screenshot 2020-10-25 231537

**Comment by Neo23x0** [comment]
It works when I set it manually to a wstring of `L"C:\\ProgramData\\Raccine\\yara"`
Screenshot 2020-10-25 233721

And it doesn't appear when I use `.c_str()`
Screenshot 2020-10-25 234644

**Comment by Eran-YT** [comment]
Try to see if you have a null character at the end of the yara_rules_dir variable, that might cause this

**Comment by Neo23x0** [comment]
I've edited the value in Registry multiple times while testing, removed it with an uninstall, added it again using: 
```
REG.EXE ADD HKLM\Software\Raccine /v RulesDir /t REG_SZ /d %ProgramData%\Raccine\yara /F
``` 

Maybe the function that reads Registry string values has an error.

**Comment by Eran-YT** [comment]
From a quick look, it seems raccineconfig::read_string_from_registry has a bug, I’ll see if I can fix it

**Comment by Eran-YT** [comment]
@Neo23x0 try to see if #71 solves this crash

**Pull request merged**
