### PR TITLE
Create handle wrapper

### PR DESCRIPTION
**Pull request by Eran-YT**

### CODE REVIEW

**Comment by Neo23x0** [comment]
We noticed that Raccine as Window application has some serious disadvantages. I'll add some screenshots made on a different machine. John also made some changes to support YARA rules and sent it to me as a ZIP archive. I merged these changes manually into a yara-matching branch that forks from the last master.

We now have two feature branches.

gui
yara-matching
The Window Application was a nice idea, but it causes too many problems in the field. I tried it on a machine and it broke some scripts and tools, since it invokes another window for a command originally sent to the command line.

**Comment by Neo23x0** [comment]
The reason, why we switched to a Window Application was the idea to show an alert message to the user. 

I had the idea to keep it a Console Application but provide another "Notification" binary that just displays the alert message.

**Comment by Neo23x0** [comment]
I'd say we should stop all feature development until the code has been cleaned up. 
Otherwise we would always get these merge problems, as we experience them now.

**Comment by Eran-YT** [comment]
This whole PR is code cleanups, should I change it so it will be based on the main branch?

**Comment by Neo23x0** [comment]
I am very sorry, but yes. It would be better to cleanup the main branch's code. 
We'll then see if we can merge the `yara-matching` branch into the master branch, when you're done.

**Comment by Omodaka9375** [comment]
> 
> 
> We noticed that Raccine as Window application has some serious disadvantages. I'll add some screenshots made on a different machine. John also made some changes to support YARA rules and sent it to me as a ZIP archive. I merged these changes manually into a yara-matching branch that forks from the last master.
> 
> We now have two feature branches.
> 
>     * `gui`
> 
>     * `yara-matching`
> 
> 
> The Window Application was a nice idea, but it causes too many problems in the field. I tried it on a machine and it broke some scripts and tools, since it invokes another window for a command originally sent to the command line.
> 
> Screenshot 2020-10-19 200300
> 
> Screenshot 2020-10-19 200020

We don't need it to be Windows app to notify the user. We can make a small message or popup.exe that will receive the message, and just pipe it to the user independently that way. And leave all dependencies to popup.exe. This has been done before for similar reasons.

**Comment by Eran-YT** [comment]
I created a new PR for this code for the main branch

**Pull request closed without merging**
