### PR TITLE
Code refactors

### PR DESCRIPTION
**Pull request by Eran-YT**
Created HandleWrapper class
Some other refactors

### CODE REVIEW

**Comment by Neo23x0** [comment]
I wonder why I see the whole file raccine.cpp as changed. 
it'll be more difficult to merge that with other developments that currently happen on that branch.

**Comment by Eran-YT** [comment]
I think it has to do with spaces vs. tabs, I'll try to fix it

**Comment by Eran-YT** [comment]
I fixed it by opening a new PR based on the current GUI branch

**Comment by Neo23x0** [comment]
We noticed that Raccine as Window application has some serious disadvantages. I'll add some screenshots made on a different machine. John also made some changes to support YARA rules and sent it to me as a ZIP archive. I merged these changes manually into a `yara-matching` branch that forks from the last `master`. 

We now have two feature branches. 
- `gui`
- `yara-matching`

The Window Application was a nice idea, but it causes too many problems in the field. I tried it on a machine and it broke some scripts and tools, since it invokes another window for a command originally sent to the command line.

**Comment by Neo23x0** [comment]
Screenshot 2020-10-19 200020
Screenshot 2020-10-19 200300

**Pull request closed without merging**
