### PR TITLE
CI: add GitHub Action to build Raccine

### PR DESCRIPTION
**Pull request by mback2k**
Work in Progress...

### CODE REVIEW

**Comment by mback2k** [comment]
Draft Status: https://github.com/mback2k/Raccine/runs/1294842005?check_suite_focus=true

**Comment by Neo23x0** [comment]
The `build_dist.bat` doesn't build the project, it just composes the package for distribution. 
I've now idea how to setup a scripted VC++ build.

**Comment by mback2k** [comment]
I got that, that is why I am also running msbuild, but seems like the GUI part is not build by that.

**Comment by mback2k** [comment]
CI workflow is fully working now: https://github.com/mback2k/Raccine/runs/1296307042

**Comment by mback2k** [comment]
Next step for another PR could be: build release artifacts via this CI pipeline. [Artifacts are currently available per commit/build](https://github.com/mback2k/Raccine/suites/1386522297/artifacts/22871318).

**Pull request merged**
